### ISSUE TITLE
`sudo` fails to run inside Lxroot

### ISSUE THREAD

**Issue by ArdvarkDev** [parke/lxroot#18] opened 2022-01-09 08:40 UTC
First of all, let me say... this program works amazingly, and is great for running glibc programs (like discord) on a musl install, without the hassle or sudo requirements of chroot.

I have found that using `lxroot -nx ./guest`, sudo will fail to run.
error message:
```
sudo: /etc/sudo.conf is owned by uid 1000, should be 0
sudo: /usr/bin/sudo must be owned by uid 0 and have the setuid bit set
```

**Comment by parke** [comment] 2022-01-09 18:55
Thanks for the report.  This is a known limitation, and is the expected behavior.  Possibly even the desired behavior.  I will provide more details and some workarounds later today.  (I don't have time right now.)

I also talk about it this video presentation.
https://www.youtube.com/watch?v=1rw7ww0k_mk

**Comment by parke** [comment] 2022-01-10 00:20
Please review the below wiki page, and let me know if you have additional questions, comments, or suggestions.

-  [Known limitations of `lxroot`](https://github.com/parke/lxroot/wiki/limitations)

**Comment by parke** [comment] 2022-01-12 17:03
I'm closing this issue, as (a) the failure of `sudo` is expected, and (b) the reason for the failure is explained at the above link.

**Closed by parke** 2022-01-12 17:04 UTC
